### ISSUE TITLE
Scripts Best Practice Not Followed

### ISSUE THREAD

**Issue by wpsmith** [gelform/kanban#17]
Currently, you are using `Kanban_Template::add_script()` and `Kanban_Template::add_style()` to output scripts and styles. Use the hooks `wp_enqueue_scripts`, `wp_print_footer_scripts`, `admin_enqueue_scripts` and `admin_print_footer_scripts` using the `wp_enqueue_script()` and `wp_enqueue_style()` functions.

Function Links
https://codex.wordpress.org/Plugin_API/Action_Reference/wp_enqueue_script
https://codex.wordpress.org/Plugin_API/Action_Reference/wp_enqueue_style

Hooks Links:
https://codex.wordpress.org/Plugin_API/Action_Reference/wp_enqueue_scripts
https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts
https://codex.wordpress.org/Plugin_API/Action_Reference/wp_print_footer_scripts
http://codex.wordpress.org/Plugin_API/Action_Reference/admin_print_footer_scripts

**Comment by gelform** [comment]
Thanks. I tried, but since I'm using a custom template, I can't have it enqueue all the scripts from the theme. Do you know of a way to empty the enqueud scripts and styles, so I can use them for my template only?

**Comment by wpsmith** [comment]
This is definitely tricky. I will see what I can come up with.
