### ISSUE TITLE
Move ALL inline JavaScript to external file

### ISSUE THREAD

**Issue by wpsmith** [gelform/kanban#19]
Move all inline JavaScript to a file. If any dynamic values need to be created use `wp_localize_script()`.

https://codex.wordpress.org/Function_Reference/wp_localize_script

**Comment by gelform** [comment]
Since I'm using a custom enque_script function, there is no wp_localize_script() available. I'll think about adding support for it, but not sure we gain anything by it other than being more wordpress-y :-)
