### ISSUE TITLE
Filter for project is not working

### ISSUE THREAD

**Issue by itinmind** [gelform/kanban#25]
I created 2 projects, they show in the dropdown of project filter but when I select one, nothing show in the box compare to the users box filter. I can select a user, see it in the box and click filter. It's working.

![2015-09-30 9-01-58 am](https://cloud.githubusercontent.com/assets/7705121/10193564/f1a2dbae-6751-11e5-8a59-75cdb85cf726.jpg)

![2015-09-30 9-02-50 am](https://cloud.githubusercontent.com/assets/7705121/10193595/12c134c0-6752-11e5-8087-5500314497f3.jpg)

**Comment by gelform** [comment]
Thanks! I'm not able to replicate this. I've made some changes to the plugin. Could you update and  check in the inspector if there is an error?

**Comment by itinmind** [comment]
It's working with the last version. Thanks.
