### ISSUE TITLE
Manage Projects

### ISSUE THREAD

**Issue by ManfredWisniewski** [gelform/kanban#26]
As far as I can tell there is no way to remove a project once it has been created. When I make a mistake in naming the project and I correct it I then have both projects as filter possibilities. As far as I can tell there is no way to remove wrong or finished projects.

PS. I guess this is work in progress? I just noticed the filters do not seem to be working at all.
I do love the project by the way and it looks really promising!

**Comment by gelform** [comment]
The filters should be working! Please test again when you get a chance.

And you're right. It's a work in progress. There's now an "edit" link on the projects drop down on a task, where you can edit projects. It might be too subtle, so I'll be adding a link to it elsewhere too.

**Comment by ManfredWisniewski** [comment]
Ok, nvm - the problem was that I didn't press the "Filter" button. I just assumed it would filter upon selection. (which would be more intuitive imo)

**Comment by ManfredWisniewski** [comment]
PS. Please also add a selector for "no project assigned" to the filter function. Sometimes projects are not saved or I forget it in the hurry of quickly adding a task. This way one can go though all the unassigned tasks quickly and assign correct projects.
I will test the updated version later this week when I have some time and let you know if the projects editor functionality works.

**Comment by gelform** [comment]
Great suggestions about the filter! Added: https://github.com/gelform/kanban-wordpress-plugin/commit/f9cd48343dfd8d3f11166853146a4237597a1dd8

**Comment by ManfredWisniewski** [comment]
Wonderful - I have tested it now and it works great! The UI might want some work in the futre but atm. it does the job like it should. :) I also like the automatic filtering upon selection much more than having to click the button!

**Comment by gelform** [comment]
I'm open to UI suggestions. Currently I'm just using Bootstrap defaults, and took a stab at placing elements.I'm hoping for user feedback (we're using it too!) to inform any changes.
