### ISSUE TITLE
duplicate settings upon reactivating plugin

### ISSUE THREAD

**Issue by ManfredWisniewski** [gelform/kanban#27]
When the plugin is deactivated and reactivated it recreates all the standard settings. (no update - just deactivate / reactivate) This leads to duplicate entries for everything If changes have been made. 

I mean Statuses, Estimates, and the saved Order

**Comment by gelform** [comment]
Great catch! This is fixed:
https://github.com/gelform/kanban-wordpress-plugin/commit/42b6e68cddeb6bfdabe92797348efbbd24abccf1
