### ISSUE TITLE
plugin deactivates wordpress navigation bar

### ISSUE THREAD

**Issue by ManfredWisniewski** [gelform/kanban#28]
The plugin removes the wordpress dash bar for the entire site. This is not ok...
Tested with Twenty Fifteen and Divi

**Comment by ManfredWisniewski** [comment]
PS. Also the redirect when logged out (to /kanban/login) points to a non existing page.

**Comment by mkrdip** [comment]
Hey, 

We can recreate the first issue you mentioned above & working on it now. Would you mind to elaborate the second one? 

Have a nice day, Cheers!

**Comment by gelform** [comment]
@ManfredWisniewski the admin bar is fixed https://github.com/gelform/kanban-wordpress-plugin/commit/4c5bf644930b94ced1806244ae16dbe1806b394f

**Comment by gelform** [comment]
@ManfredWisniewski also the /login 404 is fixed https://github.com/gelform/kanban/commit/582d461dbc1a4fb0b1b8160b85c241a168b496f4
