### ISSUE TITLE
duplicate settings upon reactivating plugin

### ISSUE THREAD

**Issue by ManfredWisniewski** [gelform/kanban#29]
The issue of the duplicate entries when reactivating the plugin has not been fixed entirely. The order of the entries is now untouched (it seems) but it still creates the standard entries for "Task Statuses" and "Task Estimates".

**Comment by gelform** [comment]
Oh, so you're saying it shouldn't recreate them if you deleted them after the first activation?

**Comment by ManfredWisniewski** [comment]
Yes - because in order to translate the plugin I renamed all the Statuses to german. When I reactivate now I have the german Status names - and additionally the standard english Status names right next to them. Same thing for the Estimates.

Why would I want them to be recreated every time I deactivate / activate the plugin?

**Comment by ManfredWisniewski** [comment]
Version 1.0 still has this issue - it recreated all the standard settings upon updating. I hope it doesn't do this everytime a new update rolls in. :(

**Comment by gelform** [comment]
@ManfredWisniewski Sorry, I forgot to update this ticket. With the new version, on activation, a global setting is saved. So now when there's another activation, it'll check for that setting, and not do updates.

If you're willing to test, if you deactivate and reactivate this version, you should see that the standard settings are not restored. 

Thanks for your help!

**Comment by ManfredWisniewski** [comment]
I just tested it, deactivating and reactivating the plugin and there are no new entries. :+1: 
Not a very thorough test but I guess the issue can be marked as resolved.
Thanks! :)

**Comment by gelform** [comment]
@ManfredWisniewski Thanks for testing!
