### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by itinmind** [gelform/kanban#3]
Hello,

I tried to activate the plugin and I got this error: Plugin could not be activated because it triggered a fatal error. **Parse error: syntax error, unexpected '[' in /hermes/bosoraweb116/b1266/nf.xxxxxxx/xxxxxx.ca/wp-content/plugins/kanban-wordpress-plugin-master/includes/class-post.php on line 151**

**WordPress 4.3.1**

**Plugins installed**
Kanban for WordPress
MainWP Child Reports
Wordfence Security
Yoast SEO

I desactivated all plugins except mine (which is mainwp child) and same error.
Fred

**Comment by gelform** [comment]
Thanks! I just pushed a fix for this.

**Comment by itinmind** [comment]
Hi, 
It's worst! I got an internal error!
**Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.**
I have to delete the plugin via FTP and it's only when I activated the plugin. I got the last version.

**Comment by gelform** [comment]
Any chance you could check your error log? I have no way of knowing what the error is to fix it :-) Thanks!

**Comment by lisaleague** [comment]
I've also tried to install via wp-admin and via sftp and get a whitescreen - 

[Tue Sep 29 23:09:41 2015] [error] [client 72.238.6.9] PHP Fatal error: Call to undefined function session_status() in /nas/wp/www/cluster-10479/sitename/wp-content/plugins/kanban-wordpress-plugin-master/includes/class-flash.php on line 23, referer: http://sitename.wpengine.com/wp-admin/update.php?action=upload-plugin

**Comment by vlood** [comment]
Issue is that session_status() works for PHP 5.4 or higher.

P.S. Fix for lower versions is replacing the check in the specified file with session_id == ''

Btw, the same line of code (23 in class-flash.php) brakes the WordPress coding standards for having a single-line if block without braces (https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style)

I'll send you a PR later today.

**Comment by itinmind** [comment]
Download last version and got the fatal error with a nice 500 screen. I will try to find the log.

**Comment by itinmind** [comment]
Upgrade to PHP 5.5 - Not more issues. I checked my PHP and I was under 5.3! Thank you.

**Comment by gelform** [comment]
Which means I need to add support for < 5.3. Thank you for your testing! I'll look into this.
