### ISSUE TITLE
Set Default Task Status Color

### ISSUE THREAD

**Issue by mkrdip** [gelform/kanban#31]
We can set default colors for our default task statuses. And each newly added task gets a random color by default. This will help users getting started with ease. Many users like to have default things. 

Currently they're set as white or blank. Screenshot below: 

![image](https://cloud.githubusercontent.com/assets/3819579/10308332/d15a071e-6c56-11e5-98c9-c1834bf934ac.png)

**Comment by ManfredWisniewski** [comment]
I would not advise going with random colors. Colors have a cultural significance and having them picked at random might go against this - not to mention it might just look strange or bland.

I am currently going with: 
yellow - green     - red  - blue  - purple
ready - progress - QA  - done - finished

**Comment by mkrdip** [comment]
Hey,

The primary colors are known to all over the globe. I proposed different default colors because by default they're set as same color #CCC, which may confuse users. :)

**Comment by ManfredWisniewski** [comment]
Ah - I read your wrong - I missed: "each newly added >task< gets a random color" and thought you meant the Status colors should be random. ;)
I totally agree with assigning random colors to new tasks! I don't think they need to copy the status color as they do right now.

**Comment by gelform** [comment]
Status colors are now set on activation (the first time). https://github.com/gelform/kanban/commit/df354b09d1dd3778b28f8e22c287745e8713fa3b
We might add the ability to add a color to tasks in the future, but I wouldn't want to make it random. Colors have meaning, so that would be confusing.
