### ISSUE TITLE
Project Name is not saved 

### ISSUE THREAD

**Issue by wpmohan** [gelform/kanban#33]
Project name is not saved when entered in project name field.

**Comment by wpmohan** [comment]
Just a bit minor design Issue ;) ![2015-10-15 14_42_41-kanban for wordpress](https://cloud.githubusercontent.com/assets/15139188/10509760/8f3f5850-734c-11e5-8851-207d985bccf6.png)

**Comment by mkrdip** [comment]
Hi Mohan,

I tried this on our board with your name & email address but couldn't replicate it. We're using exact version of the plugin you're using. :) 

![image](https://cloud.githubusercontent.com/assets/3819579/10512085/a7bf7262-735f-11e5-9f4a-ae34a2d481ca.png)

**Comment by wpmohan** [comment]
Hi Mrinal,

Thanks for your time to test this. Please find the steps as below.
1. Open the Board from Admin ' Go to your Board'.
2. Click on Add Task.
3. Enter Task name first then Project Name.
4. Repeat it for three to four tasks.
5. Refresh the browser and you will find only task names not project names.

I have attached my system details screenshot herewith.

![2015-10-15 17_24_00-support details _ tech support management](https://cloud.githubusercontent.com/assets/15139188/10513014/4e6d1a54-7362-11e5-8981-f0da73b6a0fd.png)
![2015-10-15 17_30_04-kanban for wordpress](https://cloud.githubusercontent.com/assets/15139188/10513035/6d9774ba-7362-11e5-85d5-68577df8cb58.png)

Best Regards,
Mohankumar Loganathan
wpsupport.io

**Comment by gelform** [comment]
Thanks @wpmohan I'll look into it now.

**Comment by wpmohan** [comment]
Welcome @gelform :)

**Comment by gelform** [comment]
@wpmohan can you open the inspector, and let me know if there are any javascript errors? I think maybe the project didn't save.

**Comment by wpmohan** [comment]
@gelform I don't see any javascript errors in Console. I can see two post requests happening in regular intervals. They are save_task & save_task_comment. In which parameter do you pass the project title to backend?

**Comment by gelform** [comment]
@wpmohan At this point I assume the project just never saved, so something went wrong when you initially created it. I'll dig into that. Thanks!

If you added it again, you should see an AJAX request to save it, and then a little growl alert that the project was saved. And it should then be available in the project drop down on other tasks.

**Comment by wpmohan** [comment]
@gelform For God sake you said this. I did not see the alert at all!

**Comment by gelform** [comment]
@wpmohan I'm really sorry it didn't work right the first time. I'm trying to figure out how to fix it, and I'll keep you posted.

**Comment by wpmohan** [comment]
@gelform Got it Got it !! 

Issue: Whenever an user enters the project name and navigates to task name using mouse click the project does not get saved! But project gets saved when I hit enter after entering project title and then move on to task name.

**Comment by gelform** [comment]
@wpmohan thank you so much! It's been fixed https://github.com/gelform/kanban/commit/cc35aee4d296a443e0520a363a177d95c95ec402

And I've pushed a hotfix to the WordPress plugin repo.

**Comment by wpmohan** [comment]
@gelform You're most Welcome :)
