### ISSUE TITLE
Fatal Error on Activation 

### ISSUE THREAD

**Issue by kevin-bache** [gelform/kanban#36]
Fatal error: Uncaught exception 'Exception' with message 'Freemius needs the CURL PHP extension.' in /var/www/html/wp-content/plugins/kanban/freemius/includes/sdk/Freemius.php:19 Stack trace: #0 /var/www/html/wp-content/plugins/kanban/freemius/includes/class-fs-api.php(77): require_once() #1 /var/www/html/wp-content/plugins/kanban/freemius/includes/class-fs-api.php(66): FS_Api::_init() #2 /var/www/html/wp-content/plugins/kanban/freemius/includes/class-freemius.php(6128): FS_Api::instance('kanban', 'plugin', '70', 'pk_79c5063358ba...', false) #3 /var/www/html/wp-content/plugins/kanban/freemius/includes/class-freemius.php(676): Freemius->get_api_plugin_scope() #4 /var/www/html/wp-content/plugins/kanban/freemius/includes/class-freemius.php(1020): Freemius->has_api_connectivity() #5 /var/www/html/wp-content/plugins/kanban/freemius/start.php(86): Freemius->dynamic_init(Array) #6 /var/www/html/wp-content/plugins/kanban/kanban.php(53): fs_dynamic_init(Array) #7 /var/www/html/wp-content/plugins/kanban/kanban.php(60): kan_fs() #8 in /var/www/html/wp-content/plugins/kanban/freemius/includes/sdk/Freemius.php on line 19

**Comment by gelform** [comment]
Hey, @kevin-bache Thanks for the report! We have an update coming that will detect for curl and disable freemius if it's not available. Sorry about that!

**Comment by vovafeldman** [comment]
@kevin-bache can you please open `/kanban/freemius/includes/class-fs-api.php`, search for `function test(` and share the function here. It will help me to understand what version of the SDK you are using. Thanks!

**Comment by kevin-bache** [comment]
```
    function test( $unique_anonymous_id = null ) {
        $this->_logger->entrance();

        $test = is_null( $unique_anonymous_id ) ?
            $this->_api->Test() :
            $this->_api->Test( $this->_call( 'ping.json?uid=' . $unique_anonymous_id ) );

        if ( false === $test && $this->_api->IsHttps() ) {
            // Fallback to HTTP, since HTTPS fails.
            $this->_api->SetHttp();

            self::$_options->set_option( 'api_force_http', true, true );

            $test = $this->_api->Test();
        }

        return $test;
    }
```

**Comment by vovafeldman** [comment]
Thanks @kevin-bache! As @gelform mentioned, we already fixed that and it will be deployed as part of the next Kanban release. For now, simply add the following check:

``` php
if ( ! function_exists( 'curl_version' ) ) {
    // cUrl extension is not active.
    return false;
}
```

right after:

``` php
$this->_logger->entrance();
```

Then, deactivate the plugin, and activate it again. Let me know if that worked.

**Comment by gelform** [comment]
@kevin-bache or download the latest version from here. :-)

**Comment by vovafeldman** [comment]
@gelform it looks like the latest version of Kanban on GitHub doesn't have the cURL fix in it.

**Comment by gelform** [comment]
@vovafeldman Thanks! Updated.

**Comment by kevin-bache** [comment]
Hey guys pulled the latest release but I'm still the getting same error

**Comment by kevin-bache** [comment]
Fixed it by install curl, closing the issue now
