### ISSUE TITLE
Wordpress Installed in a sub-directory causing errors

### ISSUE THREAD

**Issue by treblesand** [gelform/kanban#4]
It looks like when it created folders for the plug-in, it used the base url.  My wordpress install is in www.kjsdrafting.com/KJS/  

The plug in tried to create http://www.kjsdrafting.com/kanban/board  which gives a 404 error. I'll post any issues I find as they show up. Looking forward to it!

**Comment by treblesand** [comment]
To add to this some more information, I believe it is just the BUTTON on the welcome screen that says "Go To Board" that is leading to the wrong link.  If I manually add the directory my WP install is in, the board comes up fine.

**Comment by vlood** [comment]
Yep, it's just the wrong link in the button. Now preparing a PR for it.

**Comment by gelform** [comment]
Thanks! Your change is committed.
