### ISSUE TITLE
Not compatible with ie11

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#49]
Hello,

Thanks fors this nice job on Kanban Plugin! I'm successfull in my installation. Kanban works fine with Chrome, Edge and Safari.

But i need it Under ie11. and then I get error message. I've attached a screenshot from my Debugger.

If it works Under ie11, sure I will add the Kanban comment component!

Kind regards,

![kanbanerror](https://cloud.githubusercontent.com/assets/21235057/17958593/51a39226-6a9b-11e6-81f5-df3fb6865a74.jpg)

**Comment by gelform** [comment]
Thanks! I think I've found a fix. I'll include it in the next release.

Corey

**Comment by gsartorius** [comment]
Great news ! When do you plan to deliver the next release ?

**Comment by gelform** [comment]
We just released 2.1.10 today, with the fix included. Please let me know if you still see the issue.

Thanks!

**Comment by gsartorius** [comment]
WHOHHOOOOO ! That's wonderful, it's works fine ! Many thanks !

**Comment by gsartorius** [comment]
I get the budget yesterday. I buy the full version of the Kanban today. I keep you aware of my next stages !
