### ISSUE TITLE
New Project/Task is Invalid Post Type

### ISSUE THREAD

**Issue by treblesand** [gelform/kanban#5]
I can not add a project or task.  Says "Invalid Post Type".  It WILL let me EDIT the ones automatically created when the plugin was installed.

**Comment by wpsmith** [comment]
+1

**Comment by gelform** [comment]
Thanks! Are you trying to add through the board, or the admin? 

EDIT: never mind - I see that in the admin. Tasks and projects are only meant to be added through the board. The admin views are visible currently just for my debugging. I'll hide those for now.

**Comment by treblesand** [comment]
I couldn't access the board (see my other issue about wordpress installed in a sub-directory) so I was using the admin area.

**Comment by gelform** [comment]
I've pushed a fix to hide these pages.
