### ISSUE TITLE
Allow "View only" users to comment task

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#52]
Hello,
I thought the "View only" users were able to comment tasks. It was nice to have them not able to modify the tasks, but able to share their opinion with the developpers.
Regards,

**Comment by gelform** [comment]
Good idea. I'll add that to the feature list.

Thanks!

Corey

**Comment by gelform** [comment]
We just pushed a new version of the Advanced User Management and Comments add-ons, that add support for this. 

On the "Users" tab in the WordPress admin, you'll see a new option "Allow clients to comment":
![screenshot at sep 19 10-02-52](https://cloud.githubusercontent.com/assets/2414813/18636939/4f5484c6-7e50-11e6-9232-7e6234784a67.png)
With this switched to "Yes", view-only users will be able to comment.
