### ISSUE TITLE
Remove the title in the middle of the Kanban

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#53]
Hello,
When you have to many Kanbans, the title in the header of the kanban screen is awfully mixed with the names of the other Kanbans. Remove the main title.
Regards,

**Comment by gelform** [comment]
We added a cosmetic fix. Not perfect, but should make it easier to see all boards.

**Comment by gsartorius** [comment]
As a first step it's not so bad! Thanks for this update, this topic is no more a priority for me.

**Comment by gelform** [comment]
Good enough for me :-)
