### ISSUE TITLE
Allow "View only" users to go somewhere else than "Admin"

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#54]
My "View only" users have no access to the WP-admin interface. because the only way for same to leave kanban is to click on the "admin" button, they go directly on a "404 error page".
The ideal way will be to rename "Admin" as "Leave" and authorize us as administrator to define the URL of the exit page.
Rgds

**Comment by gelform** [comment]
Currently there's no way to remove the "admin" link. We can add a filter to that. But there are also hooks for that menu, so you can add your own "Leave" link if you want. Does that work?

**Comment by gsartorius** [comment]
Good to have another "customizable" link and keep Admin (even iif users not authorised.
Fine for me !

**Comment by gelform** [comment]
Thanks!

Corey
