### ISSUE TITLE
Define "compact view" and "show all colums" as defaulted

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#55]
I want to be able to define as already selected the "show all columns" and "compact view". I'm scared my "VIew only users" will not be geek enough to go in this menu and spend time to click on these two options.

**Comment by gelform** [comment]
We had the admin option to set these options, but took it out in favor of leaving it to the user. The problem is admin options fighting with user preferences. I'll put this on the "list" but I'll want to get a few more requests before we re-add it. Sorry about that.

**Comment by gelform** [comment]
Forgot to update. This was re-added. You can now set defaults in the admin, which can be overwritten by the user on their own machines.
