### ISSUE TITLE
Have WP-Tag or WP-Template

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#56]
Because some of my "View Only" users have no access to the Admin interface, I want to give them an easy access through the website. My feeling is a WP-Tag included in a dedicated page, or a new WP-Template, will be an easy way for me, as administrator, to provide them access to the kanban.
Kind regards,

**Comment by gelform** [comment]
There's a method `kanban_Template::get_url()` that returns the url for the board. So if you echo that, you can create a link. For example:
`<a href="<?php echo kanban_Template::get_url() ?>">Go to your board</a>` 
Will create a link that says "Go to your board" and link to the board URL.
