### ISSUE TITLE
Add a pop-up before deleting a "Kanban board"

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#57]
Hey !
Click on the delete button on the "Kanban boards" screen is so easy, I'm a little bit scared to click by error on it.....
Having a warning pop-up, i'll be less scary.
Thank you !

**Comment by gelform** [comment]
Very good point. We'll add that shortly. Thanks!

Corey

**Comment by gelform** [comment]
Forgot to update! This was added.
