### ISSUE TITLE
Enhancement: Have a "Master Board"

### ISSUE THREAD

**Issue by gsartorius** [gelform/kanban#58]
Hey,

I'm a little bit fed up to copy all the settings from one board to another.
I want to have all the boards having the same settings and modify them in a single place.

So I suggest on the bord I want, I get a checkbox : "Master settings board"
When I "check" it, any new settings done on this bord will automatically setup on all the other boards.
If I "uncheck" the box, the settings do not impact anymore the other boards.

On a "non master setting board", I may continue to overload by myself the settings.

With this kind of feature, i have to be well organize but it will be very powerfull !

Thank you !

**Comment by gelform** [comment]
Interesting idea! We're adding the ability to duplicate a board to the multiple boards add-on, which I think will let you do what you need. Hope that helps!

**Comment by gsartorius** [comment]
Hey Corey !

Great Idea to be able to duplicate, but I also want to be able to add a new function to all my boards.

So I think our two ideas may be complementary.

I’m impatient to test your duplicate function !

**Comment by gelform** [comment]
Hey, there!

Not what you were asking for, but you can now copy a board. I'll leave this issue open, tho.

Thanks!
