### ISSUE TITLE
Kanban_User::login() sanitizes password can cause password mismatch for special characters

### ISSUE THREAD

**Issue by TimothyBJacobs** [gelform/kanban#62]
The `Kanban_User::login()` function calls `sanitize_text_field()` on the password input. While fine for most passwords, it can cause an issue with passwords containing the `<` and `>` special characters. While uncommon, this is an allowed password character. See `wp_generate_password()`.

**Comment by gelform** [comment]
Good catch! I'll remove it in the next release. Thanks!
