### ISSUE TITLE
Custom CSS editor doesn't support quotes

### ISSUE THREAD

**Issue by joseluis** [gelform/kanban#63]
It's not possible right now to write selectors that need quotes, like the attribute selector:

```
#tabs-boards li.active > a[href$="-1"] {
background: red;
}
```

because both double and simple quotes are escaped, and `" "` become `\" \"` the first time you save them, and `\\" \\"` the second time, etc. And CSS rules fail.

**Comment by gelform** [comment]
Thanks! I've just committed a fix, and we'll release it shortly. https://github.com/gelform/kanban/commit/01ee61100be0f80804f4dfdde979755b2e7c1cd4
