### ISSUE TITLE
Keyboard Shortcuts - Change Hotkey

### ISSUE THREAD

**Issue by ninjatill** [gelform/kanban#65]
I find it very difficult to type within the kanban board because when I try to capitalize a word, it often activates a keyboard shortcut. For example, when creating a new task and typing into the title field, when the keyboard shortcut is activated, the focus jumps out of the task title box and I have to pause, figure out what happened, and use my mouse to place focus back into the title. There should be a way to change the keyboard shortcut hotkey from Shift, to some other key such as Control or even Shift + Control.

**Comment by gelform** [comment]
Hey, there! The issue you're describing doesn't sound like the fault of hotkeys, but rather an issue we know about when a new task is created and then added to the UI. If you're already typing, it re-adds the card under your cursor so you lose focus. Can you confirm it's a keyboard shortcut (does a modal open, for example?) or are you simply "kicked out" of the card? Thanks!

**Comment by ninjatill** [comment]
You might be right... it doesn't seem consistent. I click on the blue "+" and then click into the new task title field. It takes several clicks to get focus into that field for whatever reason. Then I start typing. I usually use good grammar/typing so I start with a capital letter. After 1 to 5 characters, I loose focus in the new task and there is a notification pop-up in the lower right of the browser for "Task Saved" (I think I enabled Chrome notifications.) Then I have to stop, re-click in the title and continue. Once I'm back in the title area, I can't reproduce the issue. I can backspace and type all I want and never trigger the issue again. So it seems that after the task creation, any typing in the title triggers a save operation and notification which causes the title to loose focus and delay entry. Or as you describe, focus would be lost first and then the save notification pops. It's not a game stopper, just annoying.

**Comment by gelform** [comment]
Okay, that definitely sounds like the scaling issues we've been noticing. We're working on a fix that should help, though won't completely eradicate the issue. And then we're making sure this is addressed in the rewritten version 3 we're working on. That should come out this summer. Sorry for the trouble!
